# Generated by Django 3.2.25 on 2025-10-27 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('vol_type', models.CharField(max_length=50)),
                ('summary_story', models.TextField()),
                ('publications', models.CharField(max_length=100)),
                ('number_of_page', models.IntegerField()),
                ('publish_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2025)], verbose_name='publish_year')),
                ('edition', models.CharField(max_length=50)),
                ('book_code', models.IntegerField()),
                ('translator', models.CharField(max_length=50)),
            ],
        ),
    ]
